apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-values
  namespace: dev
data:
  values.yaml: |
    controller:
      replicaCount: 1
      service:
        type: ClusterIP
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi
      ingressClassResource:
        name: nginx-dev
        default: false