apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-values
  namespace: staging
data:
  values.yaml: |
    controller:
      replicaCount: 2
      service:
        type: ClusterIP
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
      ingressClassResource:
        name: nginx-staging
        default: false
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - ingress-nginx
              topologyKey: kubernetes.io/hostname