apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production

resources:
- ../base

configMapGenerator:
- name: ingress-nginx-values
  files:
  - values.yaml=../values-production.yaml