apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging

resources:
- ../base

configMapGenerator:
- name: ingress-nginx-values
  options:
    disableNameSuffixHash: true
  files:
  - values.yaml=values-staging.yaml